### ISSUE TITLE
Simplify whitelist config

### ISSUE THREAD

**Issue by pkosiec** [magicmatatjahu/milv#10]
Confirm these statements before you submit the issue:

- [x] I have searched open and closed issues for duplicates.
- [x] I have read the contributing [guidelines](https://github.com/magicmatatjahu/milv/blob/master/CONTRIBUTING.md).
---

**Description**

Hi @magicmatatjahu,
First of all: Great tool!

I have an idea for simplifying the whitelist config. Currently we have:

```
  - path: "path"
    config:
      white-list-internal: ["./test.md"]
      white-list-external: ["https://foo.bar"]
```

Can't we have just `whitelist` key?

```
  - path: "path"
    config:
      whitelist: ["./test.md", "https://foo.bar"]
```

Sometimes we have false positives, which we doesn't know whether they are classified as internal or external links.

Thanks!
